# Generated by Django 5.2.7 on 2025-11-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='creatd_at',
            new_name='created_at',
        ),
    ]
